# Generated by Django 4.0 on 2023-09-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='accessLevel',
            new_name='accnumber',
        ),
    ]
