# Generated by Django 4.0 on 2023-09-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_palm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
