# Generated by Django 4.0 on 2023-09-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_remove_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palm',
            old_name='usernames',
            new_name='username',
        ),
    ]
