# Generated by Django 4.0 on 2023-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_remove_palm_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='palm',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
