# Generated by Django 4.0 on 2023-09-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_palm_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
